### ISSUE TITLE
返回固定的数据 数据里包含 @符号的时候会报错

### ISSUE THREAD

**Issue by shen-lan** [nuysoft/Mock#448]
```

module.exports = [
  {
    path: '/nested',
    component: 'Layout',
    redirect: '/nested/menu1',
    name: 'Nested',
    meta: {
      title: 'Nested',
      icon: 'nested',
      roles: ['admin', 'editor']
    },
    children: [
      {
        path: 'menu1',
        component: '@/views/nested/menu1/index', // Parent router-view
        name: 'Menu1',
        meta: {
          title: 'Menu1',
          roles: ['admin', 'editor']
        },
        children: [
          {
            path: 'menu1-1',
            component: '@/views/nested/menu1/menu1-1',
            name: 'Menu1-1',
            meta: {
              title: 'Menu1-1',
              roles: ['admin', 'editor']
            }
          },
          {
            path: 'menu1-2',
            component: '@/views/nested/menu1/menu1-2',
            name: 'Menu1-2',
            meta: {
              title: 'Menu1-2',
              roles: ['admin', 'editor']
            },
            children: [
              {
                path: 'menu1-2-1',
                component: '@/views/nested/menu1/menu1-2/menu1-2-1',
                name: 'Menu1-2-1',
                meta: {
                  title: 'Menu1-2-1',
                  roles: ['admin', 'editor']
                }
              },
              {
                path: 'menu1-2-2',
                component: '@/views/nested/menu1/menu1-2/menu1-2-2',
                name: 'Menu1-2-2',
                meta: { title: 'Menu1-2-2' }
              }
            ]
          },
          {
            path: 'menu1-3',
            component: '@/views/nested/menu1/menu1-3',
            name: 'Menu1-3',
            meta: { title: 'Menu1-3' }
          }
        ]
      },
      {
        path: 'menu2',
        component: '@/views/nested/menu2/index',
        meta: { title: 'menu2' }
      }
    ]
  }
]


```

**Comment by shen-lan** [comment]
报错提示
```
 > Mock Server hot reload success! changed  C:\Users\admin\Desktop\vue-admin-template\mock\asyncRoutes.js
request invoke:/dev-api/vue-admin-template/user/info
TypeError: Cannot read property 'nested' of undefined
    at Object.getValueByKeyPath (C:\Users\admin\Desktop\vue-admin-template\node_modules\mockjs\dist\mock.js:624:45)
    at Object.placeholder (C:\Users\admin\Desktop\vue-admin-template\node_modules\mockjs\dist\mock.js:557:24)
```

**Comment by shen-lan** [comment]
去掉 @ 符号就正常了

**Comment by wll8** [comment]
尝试使用转义字符, 例如:

``` js
Mock.mock(`@cname - \\@cname`)
```
